apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vcenter
    component: vcenter-connector
  name: vcenter-connector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vcenter
        component: vcenter-connector
    spec:
      containers:
      - name: vcenter
        image: embano1/faas-vcconnector:0.4
        command: ["./connector"]
        args: ["-vcenter", "https://vcenter.ip", "-vc-user", "vcuser", "-vc-pass", "vcpass", "-insecure", "-gateway", "http://gateway.openfaas:8080"]
      # if you do not have authentication enabled for OpenFaaS comment everything below out (incl. volumes)
        env:
          - name: basic_auth
            value: "true"
          - name: secret_mount_path
            value: "/var/secrets/"
        volumeMounts:
            - name: gateway-basic-auth
              readOnly: true
              mountPath: "/var/secrets/"
      volumes:
      - name: gateway-basic-auth
        secret:
          secretName: gateway-basic-auth