apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: vcenter
    component: vcenter-connector
  name: vcenter-connector
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: vcenter
        component: vcenter-connector
    spec:
      containers:
      - name: vcenter
        image: embano1/faas-vcconnector:0.2
        command: ["./connector"]
        args: ["-vcenter", "https://vcenter.ip", "-vc-user", "vcuser", "-vc-pass", "vcpass", "-insecure", "-gateway", "http://gateway.openfaas:8080"]
        env:
          - name: basic_auth
            value: "true"
          - name: secret_mount_path
            value: "/var/secrets/"
        volumeMounts:
            - name: auth
              readOnly: true
              mountPath: "/var/secrets/"
      # if you do not have authentication enabled for OpenFaaS comment this out 
      volumes:
      - name: auth
        secret:
          secretName: basic-auth